# Generated by Django 6.0 on 2026-02-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_job_deadline_job_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.URLField(blank=True, help_text='URL to company logo', null=True),
        ),
    ]
